---
apiVersion: v1
kind: Secret
metadata:
  name: zigbee2mqtt-secret
  namespace: home-assistant
data:
  network_key: [1, 3, 5, 7, 9, 11, 13, 15, 0, 2, 4, 6, 8, 10, 12, 13]
  mqtt_user: username
  mqtt_password: password
  # auth_token: your-secret-token
